### ISSUE TITLE
Vergleich der Einzelzeiten

### ISSUE THREAD

**Issue by georf** [Feuerwehrsport/wettkampf-manager#1]
Was passiert wenn zwei Personen die gleiche erste Zeit haben, aber die zweite Zeit bei einem nicht vorhanden ist. Wer ist dann weiter vorne?

**Comment by Schnarchbaer** [comment]
Die Person mit zwei gültigen Zeiten wird besser platziert als die Person mit nur einer gültigen Zeit. Vorschlag:Zuerst nach den schnellsten Zeiten sortieren,dann nach der Anzahl der gültigen Versuche; dann nach den schlechteren Zeiten. Brumm

**Comment by georf** [comment]
Ich habe schon mal persönlich mit anderen darüber geredet und da kamen wir in dieser Frage zu dem gleichem Schluss. Die eigentliche Frage lautet, wieso sollte sowas passieren. Das kann ja nur passieren, wenn beide einen zweiten Lauf bekommen, aber einer nicht antritt. Dann müsste der zweite aber ein D für den Nichtantritt bekommen und alles wäre klar.

Also werde ich es nach deinem Vorschlag programmieren...

Eine andere Frage: Wer bist du und möchtest du mitmachen?

**Comment by Schnarchbaer** [comment]
Hallo, der Fall kann eintreten, wenn zwei Versuche stattfinden und einer der beiden zeitgleichen Wettkämpfer im anderen Versuch eine rote Fahne sieht. Freilich ist die Häufigkeit beider Ereignisse zugleich nicht so groß.
Deine andere Frage: Ich war bis zur Jahrtausendwende in einer (lokal nicht ganz erfolglosen:-) Mannschaft und habe dann als Kampfrichter angefangen. Als ich mit kurzer Vorlaufzeit in die Auswertung eingeteilt wurde und eine Excel4.0-Tabelle vorgesetzt bekam, war ich erstmal bedient. Dann hab ich eine Access-Datenbank gemacht und mir mit ein paar VBA-Zeilen die Arbeit erleichtert. Ist aber inzwischen wohl "veraltet".Den Wettkampfmanager schaue ich mir in den nächsten Tagen an. Bis Mitte Dezember bin ich fast jeden Tag im Büro, kann also mit Vorschlägen noch dauern
Viele Grüße aus dem HarzTimo




-------- Ursprüngliche Nachricht --------
Von: Georg Limbach <notifications@github.com> 
Datum: 15.10.2015  23:10  (GMT+01:00) 
An: Feuerwehrsport/wettkampf-manager <wettkampf-manager@noreply.github.com> 
Cc: Schnarchbaer <buero.asl@timo-hulsch.de> 
Betreff: Re: [wettkampf-manager] Vergleich der Einzelzeiten (#1) 

Ich habe schon mal persönlich mit anderen darüber geredet und da kamen wir in dieser Frage zu dem gleichem Schluss. Die eigentliche Frage lautet, wieso sollte sowas passieren. Das kann ja nur passieren, wenn beide einen zweiten Lauf bekommen, aber einer nicht antritt. Dann müsste der zweite aber ein D für den Nichtantritt bekommen und alles wäre klar.

Also werde ich es nach deinem Vorschlag programmieren...

Eine andere Frage: Wer bist du und möchtest du mitmachen?
